/* GXSCC-style browser MIDI engine for JSSCC.
 * Procedural SCC-like 32-sample wavetables + GM waveform map + chiptune drums.
 * No external audio assets or APIs are used.
 */
(function () {
  "use strict";
  const LOOKAHEAD=.20,SCHEDULER_MS=35,MAX_POLYPHONY=96,TABLE_LEN=32;
  let audioCtx=null,midi=null,playbackStartCtx=0,playbackOffset=0,nextEventIndex=0,scheduler=null,lastPlayState=null,lastUiPosition=0,seekingInternally=false,activeVoices=new Map(),voiceSerial=0,masterGain=null,currentSet="scc";
  const channelState=Array.from({length:16},()=>({program:0,volume:100/127,expression:1,pan:0,bend:0,sustain:false}));
  const PROGRAM_GROUPS=[[0,45,71,73,74,79,118],[24,26,52,54,72],[25,53],[32,39],[33,36,37],[40,41,50],[44,48,81],[42,125],[1,2,9,10,11,12,28,46,47,75,78,87,102,110,111,114,115,116,117],[31,123],[4,5,127],[16,17,18],[34,35],[38,43],[20,80,83,86,89,90,91,94,99,100,113],[3,13,55,70,76,77,82,95,97,112],[8,14,15,21,23,27,84,85,88,92,93,96,98,101,103,105,108,109],[56,60],[6,106,107,124],[22],[7,104],[57,61,62,67,69],[49,63,65,66],[51,64],[29,30],[119,121],[19],[58,59,68],[120],[122,126]];
  const GM_TO_WAVE=new Uint8Array(128);PROGRAM_GROUPS.forEach((a,g)=>a.forEach(p=>GM_TO_WAVE[p]=g));
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const getUi=()=>window.ui||(typeof ui!=="undefined"?ui:null);
  const midiFreq=n=>440*Math.pow(2,(n-69)/12);
  function getAudioContext(){if(!audioCtx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error("Web Audio is not supported by this browser.");audioCtx=new AC();masterGain=audioCtx.createGain();masterGain.gain.value=.58;masterGain.connect(audioCtx.destination);}return audioCtx;}
  async function unlockAudio(){try{const c=getAudioContext();if(c.state==="suspended")await c.resume();}catch(e){console.error(e);}}
  const readU16=(v,p)=>v.getUint16(p,false),readU32=(v,p)=>v.getUint32(p,false);
  function readVar(data,state){let value=0;for(let i=0;i<4;i++){if(state.pos>=data.length)throw new Error("Unexpected end of MIDI file.");const b=data[state.pos++];value=(value<<7)|(b&127);if(!(b&128))return value;}return value;}
  function bytesToText(bytes){try{return new TextDecoder("latin1").decode(bytes);}catch(_){let o="";for(const b of bytes)o+=String.fromCharCode(b);return o;}}
  function eventOrder(t){return t==="off"?0:(t==="cc"||t==="program"||t==="bend"?1:2);}
  function parseMidi(arrayBuffer,fileName){
    const data=new Uint8Array(arrayBuffer),view=new DataView(arrayBuffer);let p=0;
    function tag(){const s=String.fromCharCode(data[p],data[p+1],data[p+2],data[p+3]);p+=4;return s;}
    if(tag()!=="MThd")throw new Error("This is not a Standard MIDI file.");const headerLen=readU32(view,p);p+=4;if(headerLen<6)throw new Error("Invalid MIDI header.");const format=readU16(view,p);p+=2,trackCount=readU16(view,p);p+=2,division=readU16(view,p);p+=2;p+=headerLen-6;if(division&32768)throw new Error("SMPTE-time MIDI files are not supported.");if(format>2)throw new Error("Unsupported MIDI format: "+format);
    const ppq=division,rawEvents=[],tempos=[{tick:0,usPerBeat:500000}];let title=(fileName||"MIDI").replace(/\.(mid|midi)$/i,"");
    for(let t=0;t<trackCount;t++){if(p+8>data.length||tag()!=="MTrk")throw new Error("Invalid MIDI track chunk.");const len=readU32(view,p);p+=4,end=Math.min(p+len,data.length),state={pos:p};let tick=0,running=0;
      while(state.pos<end){tick+=readVar(data,state);if(state.pos>=end)break;let status=data[state.pos++];if(status<128){if(!running)throw new Error("Invalid MIDI running status.");state.pos--;status=running;}else if(status<240)running=status;
        if(status===255){const type=data[state.pos++],metaLen=readVar(data,state),start=state.pos,stop=Math.min(start+metaLen,end);if(type===81&&metaLen===3)tempos.push({tick,usPerBeat:(data[start]<<16)|(data[start+1]<<8)|data[start+2]});else if(type===3&&metaLen&&(!title||title==="MIDI"))title=bytesToText(data.slice(start,stop));state.pos=stop;if(type===47)break;continue;}
        if(status===240||status===247){state.pos=Math.min(state.pos+readVar(data,state),end);continue;}
        const kind=status&240,channel=status&15,a=data[state.pos++],b=(kind===192||kind===208)?0:data[state.pos++];if(kind===144)rawEvents.push({tick,type:b?"on":"off",channel,note:a,velocity:b});else if(kind===128)rawEvents.push({tick,type:"off",channel,note:a,velocity:b});else if(kind===192)rawEvents.push({tick,type:"program",channel,value:a});else if(kind===176)rawEvents.push({tick,type:"cc",channel,controller:a,value:b});else if(kind===224)rawEvents.push({tick,type:"bend",channel,value:((b<<7)|a)-8192});}
      p=end;}
    tempos.sort((a,b)=>a.tick-b.tick);const compact=[];for(const tp of tempos){if(compact.length&&compact[compact.length-1].tick===tp.tick)compact[compact.length-1]=tp;else compact.push(tp);}let sec=0;for(let i=0;i<compact.length;i++){if(i){const prev=compact[i-1];sec+=((compact[i].tick-prev.tick)*prev.usPerBeat)/(ppq*1000000);}compact[i].seconds=sec;}
    function tickToSeconds(tick){let lo=0,hi=compact.length-1;while(lo<hi){const m=Math.ceil((lo+hi)/2);if(compact[m].tick<=tick)lo=m;else hi=m-1;}const tp=compact[lo];return tp.seconds+((tick-tp.tick)*tp.usPerBeat)/(ppq*1000000);}
    rawEvents.sort((a,b)=>a.tick-b.tick||eventOrder(a.type)-eventOrder(b.type));const events=rawEvents.map(e=>Object.assign({},e,{time:tickToSeconds(e.tick)})),duration=events.length?events[events.length-1].time+.35:0;return{format,ppq,trackCount,events,duration,title,fileName};}
  function rawWave(g){const a=new Float32Array(TABLE_LEN);for(let i=0;i<TABLE_LEN;i++){const x=i/TABLE_LEN,p=x*Math.PI*2;let v=0;switch(g){case 0:v=Math.sin(p)+.30*Math.sin(2*p)+.16*Math.sin(3*p);break;case 1:v=Math.sin(p)+.55*Math.sin(3*p)+.20*Math.sin(5*p);break;case 2:v=(x<.5?1:-1)*.92+.08*Math.sin(5*p);break;case 3:v=2*x-1;break;case 4:v=x<.25?1:-.62;break;case 5:v=1-4*Math.abs(x-.5);break;case 6:v=.78*Math.sin(p)+.40*Math.sin(4*p)+.18*Math.sin(7*p);break;case 7:v=.55*Math.sin(p)+.55*Math.sign(Math.sin(2*p));break;case 8:v=Math.sin(p)+.18*Math.sin(6*p)+.13*Math.sin(9*p);break;case 9:v=Math.sign(Math.sin(p))*.72+.28*Math.sin(3*p);break;case 10:v=.7*Math.sin(p)+.42*Math.sin(2*p)+.25*Math.sin(4*p);break;case 11:v=.72*Math.sign(Math.sin(p))+.22*Math.sign(Math.sin(3*p));break;case 12:v=x<.125?1:-.48;break;case 13:v=x<.375?1:-.74;break;case 14:v=.58*Math.sin(p)+.38*Math.sin(5*p)+.24*Math.sin(8*p);break;case 15:v=.60*(2*x-1)+.40*Math.sin(3*p);break;case 16:v=.65*Math.sin(p)+.25*Math.sin(2*p)+.20*Math.sin(7*p)+.12*Math.sin(11*p);break;case 17:v=Math.sin(p)*(.55+.45*Math.sin(2*p));break;case 18:v=.65*Math.sin(p)+.38*Math.cos(3*p)+.18*Math.sin(6*p);break;case 19:v=x<.0625?1:-.36;break;case 20:v=Math.tanh(2.7*Math.sin(p));break;case 21:v=.50*Math.sin(p)+.44*Math.sin(2*p)+.28*Math.sin(3*p)+.16*Math.sin(6*p);break;case 22:v=.75*(1-4*Math.abs(x-.5))+.25*Math.sign(Math.sin(2*p));break;case 23:v=.52*Math.sin(p)+.40*Math.sin(3*p)+.32*Math.sin(5*p)+.16*Math.sin(7*p);break;case 24:v=x<.5?(4*x-1):(3-4*x);break;case 25:v=.48*Math.sin(p)+.46*Math.sign(Math.sin(4*p));break;case 26:v=.78*Math.sin(p)+.22*Math.cos(8*p);break;case 27:v=.42*Math.sin(p)+.35*Math.sin(2*p)+.31*Math.sin(5*p)+.20*Math.sin(9*p);break;case 28:v=(Math.sin(p)>=0?1:-.35)*(i%2?.82:1);break;case 29:v=.56*Math.sin(p)+.30*Math.sign(Math.sin(3*p))+.18*Math.sin(10*p);break;default:v=Math.sin(p);}a[i]=v;}let m=0;for(const v of a)m=Math.max(m,Math.abs(v));for(let i=0;i<a.length;i++)a[i]=Math.round((a[i]/(m||1))*15)/15;return a;}
  const SCC_TABLES=Array.from({length:30},(_,i)=>rawWave(i)),SET_TABLES={square:Float32Array.from({length:32},(_,i)=>i<16?1:-1),pulse:Float32Array.from({length:32},(_,i)=>i<8?1:-.55),triangle:Float32Array.from({length:32},(_,i)=>1-4*Math.abs(i/32-.5)),sine:Float32Array.from({length:32},(_,i)=>Math.sin(i/32*Math.PI*2)),hypersin:Float32Array.from({length:32},(_,i)=>Math.tanh(2.4*Math.sin(i/32*Math.PI*2))),steel:Float32Array.from({length:32},(_,i)=>.72*Math.sin(i/32*Math.PI*2)+.28*Math.sin(i/32*Math.PI*6))};
  const periodicCache=new Map();
  function tableFor(program){if(currentSet==="scc")return SCC_TABLES[GM_TO_WAVE[program&127]];if(currentSet==="famicom"){const g=GM_TO_WAVE[program&127]%4;return g===0?SET_TABLES.square:g===1?SET_TABLES.pulse:g===2?SET_TABLES.triangle:SET_TABLES.square;}return SET_TABLES[currentSet]||SET_TABLES.square;}
  function periodicWaveFor(program){const ctx=getAudioContext(),key=currentSet+":"+(currentSet==="scc"?GM_TO_WAVE[program&127]:program&127);if(periodicCache.has(key))return periodicCache.get(key);const table=tableFor(program),real=new Float32Array(17),imag=new Float32Array(17);for(let k=1;k<17;k++){let re=0,im=0;for(let n=0;n<32;n++){const ang=2*Math.PI*k*n/32;re+=table[n]*Math.cos(ang);im-=table[n]*Math.sin(ang);}real[k]=re/16;imag[k]=im/16;}const w=ctx.createPeriodicWave(real,imag,{disableNormalization:false});periodicCache.set(key,w);return w;}
  function envelopeFor(program){const f=Math.floor((program&127)/8);if(f<=1)return{a:.004,d:.09,s:.72,r:.05};if(f===2||f===3)return{a:.003,d:.12,s:.62,r:.06};if(f===4)return{a:.002,d:.20,s:.50,r:.07};if(f===5)return{a:.025,d:.16,s:.82,r:.14};if(f===6)return{a:.012,d:.12,s:.76,r:.10};if(f===7)return{a:.018,d:.18,s:.68,r:.18};if(f===8||f===9)return{a:.006,d:.14,s:.70,r:.08};return{a:.006,d:.10,s:.68,r:.07};}
  function makeNoiseBuffer(seconds){const ctx=getAudioContext(),len=Math.max(1,Math.floor(ctx.sampleRate*seconds)),b=ctx.createBuffer(1,len,ctx.sampleRate),d=b.getChannelData(0);let l=32767;for(let i=0;i<len;i++){const bit=((l>>0)^(l>>1))&1;l=(l>>1)|(bit<<14);d[i]=(l&1)?.75:-.75;}return b;}
  function drumVoice(e,when){const ctx=getAudioContext(),gain=ctx.createGain(),pan=ctx.createStereoPanner?ctx.createStereoPanner():null,vel=e.velocity/127,n=e.note;let duration=.12,peak=.11*vel,source;if(n===35||n===36){source=ctx.createOscillator();source.type="triangle";source.frequency.setValueAtTime(n===35?105:125,when);source.frequency.exponentialRampToValueAtTime(43,when+.10);duration=.15;peak=.18*vel;}else if(n===38||n===40){source=ctx.createBufferSource();source.buffer=makeNoiseBuffer(.12);duration=.12;peak=.12*vel;}else if(n>=42&&n<=46){source=ctx.createBufferSource();source.buffer=makeNoiseBuffer(n===46?.18:.055);duration=n===46?.18:.055;peak=.07*vel;}else if(n>=41&&n<=50){source=ctx.createOscillator();source.type="triangle";const f=90+(n-41)*18;source.frequency.setValueAtTime(f*1.35,when);source.frequency.exponentialRampToValueAtTime(f,when+.08);duration=.13;peak=.12*vel;}else{source=ctx.createBufferSource();source.buffer=makeNoiseBuffer(.07);duration=.07;peak=.075*vel;}gain.gain.setValueAtTime(Math.max(.0001,peak),when);gain.gain.exponentialRampToValueAtTime(.0001,when+duration);if(pan){pan.pan.value=channelState[9].pan;source.connect(gain).connect(pan).connect(masterGain);}else source.connect(gain).connect(masterGain);source.start(when);try{source.stop(when+duration+.02);}catch(_){}updateUiChannel(9,e.note,e.velocity,0);}
  const voiceKey=(c,n,s)=>c+":"+n+":"+s;
  function stopVoice(key,when,immediate){const v=activeVoices.get(key);if(!v)return;const ctx=getAudioContext(),t=Math.max(ctx.currentTime,when||ctx.currentTime),r=immediate?.015:v.env.r;try{v.gain.gain.cancelScheduledValues(t);v.gain.gain.setValueAtTime(Math.max(.0001,v.gain.gain.value),t);v.gain.gain.exponentialRampToValueAtTime(.0001,t+r);v.osc.stop(t+r+.015);}catch(_){}activeVoices.delete(key);}
  function stopVoicesForNote(c,n,w){for(const [k,v] of Array.from(activeVoices.entries()))if(v.channel===c&&v.note===n)stopVoice(k,w,false);}
  function allNotesOff(){if(!audioCtx)return;for(const k of Array.from(activeVoices.keys()))stopVoice(k,audioCtx.currentTime,true);activeVoices.clear();const u=getUi();if(u&&u.song)for(const ch of u.song.channels)ch.volume=ch.expression=ch.output=ch.poly=0;}
  function noteOn(e,when){if(e.channel===9)return drumVoice(e,when);const ctx=getAudioContext();if(activeVoices.size>=MAX_POLYPHONY){const k=activeVoices.keys().next().value;if(k)stopVoice(k,when,true);}const st=channelState[e.channel],osc=ctx.createOscillator(),gain=ctx.createGain(),pan=ctx.createStereoPanner?ctx.createStereoPanner():null;osc.setPeriodicWave(periodicWaveFor(st.program));const ratio=Math.pow(2,(st.bend*2/8192)/12);osc.frequency.setValueAtTime(midiFreq(e.note)*ratio,when);const env=envelopeFor(st.program),vel=e.velocity/127,amp=Math.max(.0001,vel*st.volume*st.expression*.13);gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(amp,when+env.a);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,amp*env.s),when+env.a+env.d);if(pan){pan.pan.setValueAtTime(st.pan,when);osc.connect(gain).connect(pan).connect(masterGain);}else osc.connect(gain).connect(masterGain);osc.start(when);const key=voiceKey(e.channel,e.note,++voiceSerial);activeVoices.set(key,{osc,gain,pan,channel:e.channel,note:e.note,env,program:st.program,baseFreq:midiFreq(e.note)});osc.onended=()=>activeVoices.delete(key);updateUiChannel(e.channel,e.note,e.velocity,GM_TO_WAVE[st.program&127]);}
  function updateUiChannel(channel,note,velocity,waveGroup){const u=getUi();if(!u||!u.song)return;const ch=u.song.channels[channel];if(!ch)return;const st=channelState[channel];ch.volume=velocity/127;ch.expression=st.expression;ch.output=clamp((velocity/127)*st.volume*st.expression,0,1);ch.freq=Math.round(midiFreq(note));ch.panpot=st.pan;ch.pitchbend=st.bend/8192;ch.percussion=channel===9?1:0;ch.drum=channel===9;const table=channel===9?SET_TABLES.square:(currentSet==="scc"?SCC_TABLES[waveGroup]:tableFor(st.program));ch.wave=x=>table[Math.floor((((x%1)+1)%1)*32)%32];ch.poly=channel===9?1:Array.from(activeVoices.values()).filter(v=>v.channel===channel).length;}
  function applyBend(c,w){const st=channelState[c],ratio=Math.pow(2,(st.bend*2/8192)/12);for(const v of activeVoices.values())if(v.channel===c)v.osc.frequency.setTargetAtTime(v.baseFreq*ratio,w,.005);}
  function applyEvent(e,w){const st=channelState[e.channel];if(e.type==="program")st.program=e.value;else if(e.type==="cc"){if(e.controller===7)st.volume=e.value/127;else if(e.controller===11)st.expression=e.value/127;else if(e.controller===10)st.pan=clamp((e.value-64)/63,-1,1);else if(e.controller===64)st.sustain=e.value>=64;else if(e.controller===120||e.controller===123)for(const [k,v] of Array.from(activeVoices.entries()))if(v.channel===e.channel)stopVoice(k,w,true);}else if(e.type==="bend"){st.bend=e.value;applyBend(e.channel,w);}else if(e.type==="on")noteOn(e,w);else if(e.type==="off"&&!st.sustain)stopVoicesForNote(e.channel,e.note,w);}
  function eventIndexAt(s){if(!midi)return 0;let lo=0,hi=midi.events.length;while(lo<hi){const m=(lo+hi)>>1;if(midi.events[m].time<s)lo=m+1;else hi=m;}return lo;}
  function resetChannelStates(){for(const st of channelState)Object.assign(st,{program:0,volume:100/127,expression:1,pan:0,bend:0,sustain:false});}
  function currentPlaybackSeconds(){if(!audioCtx||!midi)return playbackOffset;const u=getUi();return u&&u.song&&u.song.playState===PlayState.PLAYING?Math.max(0,playbackOffset+audioCtx.currentTime-playbackStartCtx):playbackOffset;}
  function rebuildStateAt(s){resetChannelStates();const idx=eventIndexAt(s);for(let i=0;i<idx;i++){const e=midi.events[i],st=channelState[e.channel];if(e.type==="program")st.program=e.value;else if(e.type==="cc"){if(e.controller===7)st.volume=e.value/127;else if(e.controller===11)st.expression=e.value/127;else if(e.controller===10)st.pan=clamp((e.value-64)/63,-1,1);else if(e.controller===64)st.sustain=e.value>=64;}else if(e.type==="bend")st.bend=e.value;}}
  function setPosition(s){if(!midi)return;playbackOffset=clamp(s,0,midi.duration);allNotesOff();rebuildStateAt(playbackOffset);nextEventIndex=eventIndexAt(playbackOffset);if(audioCtx)playbackStartCtx=audioCtx.currentTime;}
  function startPlayback(){if(!midi)return;unlockAudio();if(playbackOffset>=midi.duration-.01)setPosition(0);const ctx=getAudioContext();playbackStartCtx=ctx.currentTime;nextEventIndex=eventIndexAt(playbackOffset);if(!scheduler)scheduler=setInterval(scheduleAhead,SCHEDULER_MS);scheduleAhead();}
  function pausePlayback(){playbackOffset=currentPlaybackSeconds();allNotesOff();}function stopPlayback(reset){allNotesOff();if(reset)setPosition(0);}
  function scheduleAhead(){const u=getUi();if(!midi||!audioCtx||!u||!u.song||u.song.playState!==PlayState.PLAYING)return;const now=currentPlaybackSeconds(),h=now+LOOKAHEAD;while(nextEventIndex<midi.events.length&&midi.events[nextEventIndex].time<=h){const e=midi.events[nextEventIndex++];applyEvent(e,audioCtx.currentTime+Math.max(0,e.time-now));}if(midi.duration>0){const pos=Math.min(1,now/midi.duration);seekingInternally=true;u.song.position=pos;lastUiPosition=pos;seekingInternally=false;}if(now>=midi.duration){if(u.song.repeat){setPosition(0);playbackStartCtx=audioCtx.currentTime;}else{u.song.playState=PlayState.STOPPED;stopPlayback(true);}}}
  function syncWithExistingUi(){const u=getUi();if(!u||!u.song||typeof PlayState==="undefined")return;const state=u.song.playState;if(lastPlayState===null)lastPlayState=state;if(state!==lastPlayState){if(state===PlayState.PLAYING)startPlayback();else if(state===PlayState.PAUSED)pausePlayback();else if(state===PlayState.STOPPED)stopPlayback(true);else if(state===PlayState.FASTFORWARD&&midi){setPosition(currentPlaybackSeconds()+10);u.song.playState=PlayState.PLAYING;startPlayback();}lastPlayState=u.song.playState;}if(midi&&!seekingInternally&&Math.abs((u.song.position||0)-lastUiPosition)>.015){setPosition(clamp(u.song.position||0,0,1)*midi.duration);lastUiPosition=u.song.position||0;if(u.song.playState===PlayState.PLAYING&&audioCtx)playbackStartCtx=audioCtx.currentTime;}}
  function refreshRenderer(){const u=getUi();if(!u||!u.renderer||!u.renderer.initialized)return;try{for(let i=0;i<16;i++)u.renderer.drawChannel(i);u.renderer.drawDGroup("positionSlider");}catch(_){}}
  async function loadFile(file){if(!file)return;if(!/\.(mid|midi)$/i.test(file.name))return showToast("Please drop a .mid or .midi file",true);try{showToast("Loading "+file.name+"…");const parsed=parseMidi(await file.arrayBuffer(),file.name);if(!parsed.events.some(e=>e.type==="on"))throw new Error("No note events found.");stopPlayback(true);midi=parsed;playbackOffset=0;nextEventIndex=0;resetChannelStates();const u=getUi();if(u&&u.song){u.song.fileName=parsed.fileName;u.song.position=0;u.song.playState=PlayState.STOPPED;}lastPlayState=PlayState.STOPPED;lastUiPosition=0;refreshRenderer();showToast("Loaded: "+parsed.fileName+" — "+formatTime(parsed.duration)+" — "+setLabel(currentSet));}catch(err){console.error(err);showToast("Could not load MIDI: "+(err&&err.message?err.message:err),true);}}
  function formatTime(s){s=Math.max(0,Math.round(s));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0");}
  function setLabel(s){return({scc:"SCC LIKE",famicom:"FAMICOM LIKE",square:"ALL SQUARE",pulse:"ALL PULSED SQUARE",triangle:"ALL TRIANGLE",hypersin:"ALL HYPERSIN",steel:"ALL STEEL",sine:"ALL SINE"})[s]||s;}
  let toastTimer=null;function showToast(text,error){let el=document.getElementById("midi-toast");if(!el){el=document.createElement("div");el.id="midi-toast";Object.assign(el.style,{position:"fixed",left:"50%",bottom:"18px",transform:"translateX(-50%)",zIndex:"9999",font:"14px monospace",padding:"9px 13px",border:"1px solid currentColor",background:"rgba(0,0,0,.86)",color:"#fff",pointerEvents:"none",maxWidth:"calc(100vw - 30px)",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"});document.body.appendChild(el);}el.textContent=text;el.style.color=error?"#ff8b8b":"#fff";el.style.opacity="1";clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.style.opacity="0";},error?5000:3200);}
  function makeDropOverlay(){const o=document.createElement("div");o.id="midi-drop-overlay";o.textContent="DROP MIDI FILE";Object.assign(o.style,{display:"none",position:"fixed",inset:"12px",zIndex:"9998",alignItems:"center",justifyContent:"center",border:"3px dashed currentColor",background:"rgba(0,0,0,.68)",color:"white",font:"bold 26px monospace",pointerEvents:"none"});document.body.appendChild(o);return o;}
  function initInput(){const overlay=makeDropOverlay();let dragDepth=0;window.addEventListener("dragenter",e=>{if(e.dataTransfer&&Array.from(e.dataTransfer.types||[]).includes("Files")){e.preventDefault();dragDepth++;overlay.style.display="flex";}});window.addEventListener("dragover",e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect="copy";});window.addEventListener("dragleave",e=>{e.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)overlay.style.display="none";});window.addEventListener("drop",e=>{e.preventDefault();dragDepth=0;overlay.style.display="none";unlockAudio();loadFile(e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0]);});
    const picker=document.createElement("input");picker.type="file";picker.accept=".mid,.midi,audio/midi,audio/x-midi";picker.hidden=true;picker.addEventListener("change",()=>{unlockAudio();loadFile(picker.files&&picker.files[0]);picker.value="";});document.body.appendChild(picker);
    const controls=document.createElement("div");Object.assign(controls.style,{position:"fixed",right:"12px",bottom:"12px",zIndex:"9997",display:"flex",gap:"6px"});const select=document.createElement("select");[["scc","SCC LIKE"],["famicom","FAMICOM LIKE"],["square","ALL SQUARE"],["pulse","ALL PULSED SQUARE"],["triangle","ALL TRIANGLE"],["hypersin","ALL HYPERSIN"],["steel","ALL STEEL"],["sine","ALL SINE"]].forEach(([v,t])=>{const o=document.createElement("option");o.value=v;o.textContent=t;select.appendChild(o);});Object.assign(select.style,{font:"bold 12px monospace",padding:"7px 8px",border:"1px solid currentColor",background:"rgba(0,0,0,.82)",color:"white"});select.value=currentSet;select.addEventListener("change",()=>{currentSet=select.value;periodicCache.clear();allNotesOff();if(midi)rebuildStateAt(currentPlaybackSeconds());showToast("Instrument set: "+setLabel(currentSet));});
    const button=document.createElement("button");button.type="button";button.textContent="LOAD MIDI";Object.assign(button.style,{font:"bold 12px monospace",padding:"7px 10px",cursor:"pointer",border:"1px solid currentColor",background:"rgba(0,0,0,.82)",color:"white"});button.addEventListener("click",()=>picker.click());controls.appendChild(select);controls.appendChild(button);document.body.appendChild(controls);document.addEventListener("pointerdown",unlockAudio,{passive:true});}
  window.JSSCCMidi={loadFile,parseMidi,get current(){return midi;},get instrumentSet(){return currentSet;},set instrumentSet(v){currentSet=v;periodicCache.clear();}};
  window.addEventListener("DOMContentLoaded",()=>{initInput();setInterval(syncWithExistingUi,40);setInterval(refreshRenderer,100);showToast("Drop a .mid/.midi file — default: SCC LIKE");});
})();
